### PR TITLE
add cron.yaml

### LINKED ISSUE #34: Add Cron.yaml
Add cron job to distribution/kubeflow/pipelines from https://github.com/StatCan/aaw-kubeflow-manifest/blob/master/.github/workflows/cron.yml

### PR DESCRIPTION
**Pull request by rohank07**
Add cron.yaml 
https://github.com/StatCan/aaw-kubeflow-manifest/blob/master/.github/workflows/cron.yml

### CODE REVIEW

**Comment by Jose-Matsuda** [comment]
I could be mistaken but shouldn't this go under the `.github/workflows` folder and not under distribution?
EDIT: 
image


* Should be a kubernetes cronjob and not a github action

**Comment by blairdrummond** [comment]
Can we add this to aaw-argocd-manifests instead?

**Comment by Jose-Matsuda** [comment]
Just a note for future Jose to test this you should probably just change the command to run every minute and watch it, and maybe change the kubectl command to delete something I know exists and see if it can. 

Btw changed to 
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-cleanup-workflows
spec:
  concurrencyPolicy: Allow
  schedule: "*/1 * * * *"
  jobTemplate:  
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command:
            - kubectl delete namespace test-1
          restartPolicy: OnFailure
```

But after describing the created pod it fails with
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  32s                default-scheduler  Successfully assigned default/cron-cleanup-workflows-27242085-pzb78 to argoflow-worker
  Normal   Pulled     16s (x3 over 32s)  kubelet            Container image "bitnami/kubectl:latest" already present on machine
  Normal   Created    16s (x3 over 31s)  kubelet            Created container cron
  Warning  Failed     16s (x3 over 31s)  kubelet            Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "kubectl delete namespace test-1": executable file not found in $PATH: unknown
  Warning  BackOff    2s (x4 over 29s)   kubelet            Back-off restarting failed container
```

**Comment by rohank07** [comment]
Closing PR. Moving to aaw-argocd-manifests

**Pull request closed without merging**
